config:
  install_tree: $SOFTS_DIR_PATH/install
  module_roots:
    tcl: $SOFTS_DIR_PATH/modules/tcl
  build_stage:
  - $tempdir
  - $SOFTS_DIR_PATH/.stage
  install_path_scheme: '${ARCHITECTURE}/${COMPILERNAME}-${COMPILERVER}/${PACKAGE}-${VERSION}-${HASH:6}'
  verify_ssl: false
