config:
  install_tree:
    root: $SPACK_INSTALL_PREFIX
    projections:
      all: ${ARCHITECTURE}/${COMPILERNAME}-${COMPILERVER}/${PACKAGE}-${VERSION}-${HASH:10}
  source_cache: $SPACK_INSTALL_PREFIX/.cache
  module_roots:
    tcl: $SPACK_INSTALL_PREFIX/modules/tcl
    lmod: $SPACK_INSTALL_PREFIX/modules/lmod
  build_stage:
  - $tempdir
  - $SPACK_INSTALL_PREFIX/.stage
  install_missing_compilers: true
  build_jobs: 12
