packages:
    atk:
        paths:
            atk@2.22.0: /usr
        version: [2.22.0]
    autoconf:
        paths:
            autoconf@2.69: /usr
        version: [2.69]
    automake:
        paths:
            automake@1.13.4: /usr
        version: [1.13.4]
    bison:
        paths:
            bison@3.0.4: /usr
        version: [3.0.4]
    boost:
        variants: +pic
    cairo:
        paths:
            cairo@1.8.10: /usr
        version: [1.8.10]
    cuda:
        version: [9.2.88]
    curl:
        paths:
            curl@7.29.0: /usr
        version: [7.29.0]
    eigen:
        variants: ~fftw~gmp~metis~mpfr~scotch
    flex:
        paths:
            flex@2.5.37: /usr
        version: [2.5.37]
    fontconfig:
        paths:
            fontconfig@2.10.95: /usr
        version: [2.10.95]
    gtkplus:
        paths:
            gtkplus@2.24.31: /usr
        version: [2.24.31]
    hadoop:
        version: [2.9.0]
    hdf5:
        variants: +hl
    intel-mkl:
        version: [2018.3.222]
    # Drags in heavy PEARL dependencies
    intltool:
        paths:
            intltool@0.50.2: /usr
        version: [0.50.2]
    julia:
        variants: +external_llvm
    libjpeg:
        paths:
            libjpeg@1.2.90: /usr
        version: [1.2.90]
    libgcrypt:
        paths:
            libgcrypt@1.5.3: /usr
        version: [1.5.3]
    libmng:
        paths:
            libmng@1.0.10: /usr
        version: [1.0.10]
    libtool:
        paths:
            libtool@2.4.2: /usr
        version: [2.4.2]
    llvm:
        variants: +link_dylib
    m4:
        paths:
            m4@1.4.16: /usr
        version: [1.4.16]
    ncurses:
        paths:
            ncurses@5.9: /usr
        version: [5.9]
    # can not be installed with python 3
    node-js:
        paths:
            node-js@6.12.2: /usr
        version: [6.12.2]
    openssl:
        paths:
            openssl@1.0.2k: /usr
        version: [1.0.2k]
    opengl:
        paths:
            opengl@4.5: /usr
        buildable: False
        version: [4.5]
    pango:
        paths:
            pango@1.40.4: /usr
        version: [1.40.4]
    pcre:
        paths:
            pcre@8.32+jit+utf: /usr
        version: [8.32]
    perl:
        paths:
            perl@5.16.3: /usr
        version: [5.16.3]
    petsc:
        variants: ~fortran
    pkg-config:
        paths:
            pkg-config@0.27.1: /usr
        version: [0.27.1]
    python:
        version: [3.7.4]
    slurm:
        paths:
            slurm@17.02: /usr
        buildable: False
        version: [17.02]
    steps:
        variants: +lapack+petsc+mpi
    tar:
        paths:
            tar@1.26: /usr
        version: [1.26]
    tk:
        paths:
            tk@8.5.13: /usr
        version: [8.5.13]
    trilinos:
        variants: +kokkos+teuchos+openmp~amesos~amesos2~aztec~epetra~epetraext~hypre~ifpack~ifpack2~superlu-dist~mumps~muelu~metis~suite-sparse~tpetra~zoltan~zoltan2
        version: [xsdk-0.4.0-rc1]
    xz:
        paths:
            xz@5.2: /usr
        version: [5.2]
    all:
        compiler: [gcc@6.4.0, intel@18.0.1]
        providers:
            mpi: [hpe-mpi, intel-mpi]
            scalapack: [intel-mkl, netlib-scalapack]
            lapack: [intel-mkl, openblas]
            blas: [intel-mkl, openblas]
