packages:
    autoconf:
        paths:
            autoconf@2.69: /usr
        version: [2.69]
    automake:
        paths:
            automake@1.13.4: /usr
        version: [1.13.4]
    bison:
        paths:
            bison@3.0.4: /usr
        version: [3.0.4]
    boost:
        variants: +pic
    cuda:
        version: [9.2.88]
    curl:
        paths:
            curl@7.29.0: /usr
        version: [7.29.0]
    darshan-runtime:
        variants: +slurm
    eigen:
        variants: ~fftw~gmp~metis~mpfr~scotch
    flex:
        paths:
            flex@2.5.37: /usr
        version: [2.5.37]
    hadoop:
        version: [2.9.2]
    hdf5:
        variants: +hl
    icu4c:
        version: [64.1]
    intel-mkl:
        version: [2018.3.222]
    # Drags in heavy PEARL dependencies
    intltool:
        paths:
            intltool@0.50.2: /usr
        version: [0.50.2]
    julia:
        variants: +external_llvm
    libtool:
        paths:
            libtool@2.4.2: /usr
        version: [2.4.2]
    llvm:
        variants: +link_dylib
    m4:
        paths:
            m4@1.4.16: /usr
        version: [1.4.16]
    # can not be installed with python 3
    node-js:
        paths:
            node-js@6.12.2: /usr
        version: [6.12.2]
    openssl:
        paths:
            openssl@1.0.2k: /usr
        version: [1.0.2k]
    opengl:
        paths:
            opengl@4.5: /usr
        buildable: False
        version: [4.5]
    perl:
        paths:
            perl@5.16.3: /usr
        version: [5.16.3]
    petsc:
        variants: ~fortran
    python:
        variants: +tk
        version: [3.8.3]
    qt:
        variants: ~sql~tools
    slurm:
        paths:
            slurm@17.02: /usr
        buildable: False
        version: [17.02]
    steps:
        variants: +lapack+petsc+mpi
    superlu-dist:
        variants: +int64
    tar:
        paths:
            tar@1.28: /usr
        version: [1.28]
    timemory:
        variants: +mpi~cuda+cupti+caliper~gperftools~python@3.0.0a
    trilinos:
        variants: +kokkos+teuchos+openmp~amesos~hypre~superlu-dist~mumps~metis~suite-sparse
        version: [xsdk-0.4.0-rc1]
    all:
        compiler: [gcc@9.3.0, intel@19.1.1.217, gcc@4.8.5]
        target: [x86_64]
        providers:
            mpi: [hpe-mpi, intel-mpi]
            scalapack: [intel-mkl, netlib-scalapack]
            lapack: [intel-mkl, openblas]
            blas: [intel-mkl, openblas]
