spack:
  view: false
  concretization: separately
  packages:
    all:
      compiler: [gcc@4.8.5]
    intel-parallel-studio:
      variants: +advisor+clck+daal+gdb+inspector+ipp+itac+mkl+mpi+rpath+shared+tbb+vtune
  specs:
    - gcc@9.3.0
    - gcc@10.2.0
    - intel@20.0.2
    - intel-parallel-studio@professional.2020.1
