spack:
  view: false
  concretization: separately
  packages:
    all:
      compiler: [gcc@9.3.0]
      providers:
        jpeg: [libjpeg-turbo]
        mpi: [hpe-mpi]
        lapack: [intel-mkl@2019.3.199]
    cairo:
      variants: +pdf+png
    graphviz:
      variants: +pangocairo
    mvapich2:
      variants: fabrics=mrail process_managers=slurm file_systems=gpfs
    pgi:
      variants: +network+nvidia+mpi
    python:
      version: [3.8.3]
    timemory:
      variants: +mpi~cuda~cupti+caliper~gperftools~python
  specs:
    - llvm@11.0.0 +cuda cuda_arch=70 +omp_tsan +python ^cuda@11.1.0
    - nvhpc@20.9 install_type=network
    - arm-forge@20.0.3-Redhat-7.0-x86_64
    - blender
    - cmake@3.15.3
    - darshan-runtime
    - darshan-util
    - doxygen@1.8.15
    - emacs@26.1
    - environment-modules@4.5.1
    - ffmpeg
    - gdb~python@8.2
    - git@2.18.0
    - graphviz@2.42.2
    - help2man@1.47.4
    - hpctoolkit@2019.08.14
    - hpcviewer@2020.05
    - hpe-mpi@2.22.hmpt
    - intel-mpi@2019.7.217
    - ispc@1.12.0
    - mvapich2@2.3
    - stat@4.0.2.999
    - valgrind~mpi@3.15.0
    - boost~mpi@1.73.0
    - bzip2@1.0.6
    - cgal
    - cuda@10.1.243
    - cuda@11.1.0
    - cudnn@7.3.0.29-9.0-linux-x64
    - glew
    - gmsh+metis~mpi+oce+openmp+shared@4.4.1
    - hdf5~mpi@1.10.5
    - intel-mkl@2019.3.199
    - julia
    - libxml2
    - libxslt
    - ncurses
    - ninja@1.8.2
    - openblas@0.3.10
    - optix
    - python@3.8.3
    - qhull@2015.2
    - qt@5.14.2
    - readline
    - snakemake
    - sqlite
    - symengine@0.3.0
    - virtualgl
    - vrpn
    - zlib@1.2.11
    - libzmq+libsodium@4.3.2%intel@19.1.1.217
    - timemory@3.0.1
